<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>1.0.0</Version>
    <AssemblyName>TagSeeker</AssemblyName>
    <Product>TagSeeker</Product>
    <Authors>TagSeeker</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.16.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.8.0.20230708" />
    <PackageReference Include="Sdcb.PaddleInference" Version="2.5.0.1" />
    <PackageReference Include="Sdcb.PaddleInference.runtime.win64.mkl" Version="2.5.0" />
    <PackageReference Include="Sdcb.PaddleOCR" Version="2.7.0.3" />
    <PackageReference Include="Sdcb.PaddleOCR.Models.Local" Version="2.7.0" />
    <PackageReference Include="Sdcb.PaddleOCR.Models.LocalV4" Version="2.7.0.1" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
  </ItemGroup>

</Project>
